server:
  port: 8091

spring:
  application:
    name: sitebackend-global-erp
  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5431}/${ERP_PG_DATABASE:erp_database}
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  task:
    execution:
      pool:
        core-size: 4
        max-size: 8
        queue-capacity: 100
  mail:
    host: smtp.yandex.ru
    port: 465
    username: malinovskiy.denis@yandex.ru
    password: password
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.connectiontimeout: 10000
      mail.smtp.timeout: 10000
      mail.smtp.writetimeout: 10000
      mail.debug: true

  mongodb:
    uri: ${MONGO_DB_URI:mongodb://mongo_user:mongo_password@localhost:27017/crackhack_db_mongo?authSource=admin}

student-certificate:
  position:
    fio:
      x: 170
      y: 475
    course:
      x: 130
      y: 535
  filename-template: participant_cert_%s_%s

entity-factory:
  kafka:
    consumer:
      config:
        bootstrap-servers: ${KAFKA_URL:localhost:9092}
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        auto-offset-reset: earliest
