create table companies (
  id int primary key not null generated by default as identity,
  company_code varchar(255) not null unique,
  company_name varchar(255) not null,
  external_company_code varchar(255)
);

create table courses (
  id int primary key not null generated by default as identity,
  name varchar(255) not null,
  description varchar(1024) not null,
  duration_in_days int not null,
  price_per_person decimal(12, 2) not null,
  external_id int,
  external_code varchar(255),
  unique (external_id, external_code)
);

create table specifications (
  id int primary key not null generated by default as identity,
  datetime timestamp not null,
  number int not null,
  company_id int not null references companies(id),
  total_amount_excluding_vat decimal(12, 2) not null,
  vat_amount_22_percent decimal(12, 2) not null,
  total_amount_including_vat decimal(12, 2) not null
);

create table course_completion_statuses (
  id int primary key not null generated by default as identity,
  name varchar(255) not null unique
);
insert into course_completion_statuses (name) values ('PLANNING'),
                                                     ('IN_PROCESS'),
                                                     ('COMPLETED');

create table groups (
  id int primary key not null generated by default as identity,
  course_id int not null references courses(id),
  date_begin timestamp not null,
  date_end timestamp not null,
  price_per_person decimal(12, 2) not null,
  course_completion_id int not null references course_completion_statuses(id),
  average_progress float not null,
  specification_id int not null references specifications(id)
);

create table students (
    id int primary key not null generated by default as identity,
    first_name varchar(255) not null,
    middle_name varchar(255) not null,
    last_name varchar(255) not null,
    company_id int not null references companies(id),
    email varchar(255) not null unique,
    external_id int,
    external_code varchar(255),
    unique (external_id, external_code)
);

create table group_members (
  id int not null generated by default as identity,
  student_id int not null references students(id),
  group_id int not null references groups(id),
  completion_percent decimal(3, 2) not null default 0.00,
  certificate_id varchar(255),
  unique (student_id, group_id)
);
